extends Node

enum services {
	CIRCLE, CROSS,  SQUARE,  TRIANGLE,  CRESCENT,  PUPPY,  RIVER,  STAR,  CHAIN,  GUST,
		   SCROSS, SSQUARE, STRIANGLE, SCRESCENT, SPUPPY, SRIVER, SSTAR, SCHAIN, SGUST
}

var service_prices = [10, 2, 2, 2, 2, 4, 4, 6, 6, 8]
